### ISSUE TITLE
FilterBuilder doesn't seem to filter "active" clients correctly

### ISSUE THREAD

**Issue by L422Y** [freshbooks/freshbooks-python-sdk#42]
```
fb_filter = FilterBuilder()
fb_filter.boolean("active", True)
clients = freshbooks_client.clients.list(account_id, builders=[fb_filter])
clients = clients.data['clients']
```

I expected this to only return active / non-archived clients... but the list doesn't seem to change whether I use the filter or not, any ideas? The docs are pretty vague on this unfortunately...

**Comment by amcintosh** [comment]
Hi.  
Our accounting endpoints don't have an "active" filter. They use a `vis_state` property to show their status with 0=active, 1=deleted, and 2=archived. This is [documented here](https://www.freshbooks.com/api/active_deleted). By defaults the list method returns all active and archived clients. 

You can specify only active clients with:

```python
fb_filter = FilterBuilder()
fb_filter.equals("vis_state", 0)
clients = freshbooks_client.clients.list(account_id, builders=[fb_filter])
```

You can see a list of the search filters available on the [client endpoint here](https://www.freshbooks.com/api/clients) under "Searches / Filters".

Hope that helps.

**Comment by L422Y** [comment]
Great, thanks!

This [Filters documentation](https://freshbooks-python-sdk.readthedocs.io/en/latest/user_guide/making_calls.html#filters) somewhat indirectly suggests / implies that there's an `active` property, so that's where I was getting confused.

**Comment by amcintosh** [comment]
Indeed it does. Thanks. I'll address that.
