### ISSUE TITLE
Response errors in client are not very descriptive

### ISSUE THREAD

**Issue by schapman1974** [freshbooks/freshbooks-python-sdk#52]
https://github.com/freshbooks/freshbooks-python-sdk/blob/main/freshbooks/client.py#L155

The response json contains much better information.  The try / except below this should do a bit more in the key error to determine if content has error messages.  
Example error message:
    {'error': 'invalid_grant', 'error_description': 'The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'}

For instance this line
https://github.com/freshbooks/freshbooks-python-sdk/blob/main/freshbooks/client.py#L163
```python
        raise FreshBooksError(response.status_code, "Failed to fetch access_token", raw_response=response.text)
```

could look something like this
```python
         raise FreshBooksError(
              response.status_code,
              content["error"] if content and content.get("error") else "Failed to fetch access_token",
              raw_response=content["error_description"] if content and content.get("error_description") else response.text
         )
``` 
It would keep what is already there unless an actual error came through from freshbooks.

**Comment by amcintosh** [comment]
Hi! Thank you for raising this. We've made some changes to expose the error message and pushed a release.
